#include "Compiler.h"
#include "../../runtime/UI/UISDL.h"

void Compiler::CreateConstant(const std::string &name, Primitive type, llvm::Constant *val) {
    InstanceConstant::Build(name, type, Scope::GLOBAL, llvm, GetIR());
    llvm.CreateConstant(name, type, val);
}

void Compiler::Constants() {
    CreateConstant("WINDOWED", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, 1));
    CreateConstant("BANKED", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, 2));

    CreateConstant("KEY_ESCAPE", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_ESCAPE));
    CreateConstant("KEY_RETURN", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_RETURN));

    // Constants
    CreateConstant("KEY_1", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_1));
    CreateConstant("KEY_2", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_2));
    CreateConstant("KEY_3", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_3));
    CreateConstant("KEY_4", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_4));
    CreateConstant("KEY_5", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_5));
    CreateConstant("KEY_6", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_6));
    CreateConstant("KEY_7", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_7));
    CreateConstant("KEY_8", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_8));
    CreateConstant("KEY_9", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_9));
    CreateConstant("KEY_0", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_0));

    CreateConstant("KEY_Q", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_Q));
    CreateConstant("KEY_W", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_W));
    CreateConstant("KEY_E", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_E));
    CreateConstant("KEY_R", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_R));
    CreateConstant("KEY_T", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_T));
    CreateConstant("KEY_Y", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_Y));
    CreateConstant("KEY_U", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_U));
    CreateConstant("KEY_I", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_I));
    CreateConstant("KEY_O", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_O));
    CreateConstant("KEY_P", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_P));

    CreateConstant("KEY_A", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_A));
    CreateConstant("KEY_S", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_S));
    CreateConstant("KEY_D", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_D));
    CreateConstant("KEY_F", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_F));
    CreateConstant("KEY_G", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_G));
    CreateConstant("KEY_H", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_H));
    CreateConstant("KEY_J", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_J));
    CreateConstant("KEY_K", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_K));
    CreateConstant("KEY_L", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_L));

    CreateConstant("KEY_Z", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_Z));
    CreateConstant("KEY_X", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_X));
    CreateConstant("KEY_C", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_C));
    CreateConstant("KEY_V", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_V));
    CreateConstant("KEY_B", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_B));
    CreateConstant("KEY_N", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_N));
    CreateConstant("KEY_M", Primitive::INT, llvm.CreateConstantInt(Primitive::INT, SDL_SCANCODE_M));

/*    constants.insert(std::make_pair("CHANNEL_SINE%", llvm::ConstantInt::get(llvm->TypeInt, 0)));
    constants.insert(std::make_pair("CHANNEL_SQUARE%", llvm::ConstantInt::get(llvm->TypeInt, 1)));
    constants.insert(std::make_pair("CHANNEL_TRIANGLE%", llvm::ConstantInt::get(llvm->TypeInt, 2)));
    constants.insert(std::make_pair("CHANNEL_SAWTOOTH%", llvm::ConstantInt::get(llvm->TypeInt, 3)));
    constants.insert(std::make_pair("CHANNEL_NOISE%", llvm::ConstantInt::get(llvm->TypeInt, 4)));
    constants.insert(std::make_pair("CHANNEL_PULSE5%", llvm::ConstantInt::get(llvm->TypeInt, 5)));
    constants.insert(std::make_pair("CHANNEL_PULSE10%", llvm::ConstantInt::get(llvm->TypeInt, 6)));
    constants.insert(std::make_pair("CHANNEL_PULSE15%", llvm::ConstantInt::get(llvm->TypeInt, 7)));
    constants.insert(std::make_pair("CHANNEL_PULSE20%", llvm::ConstantInt::get(llvm->TypeInt, 8)));
    constants.insert(std::make_pair("CHANNEL_PULSE25%", llvm::ConstantInt::get(llvm->TypeInt, 9)));
    constants.insert(std::make_pair("CHANNEL_PULSE50%", llvm::ConstantInt::get(llvm->TypeInt, 10)));
    constants.insert(std::make_pair("CHANNEL_PULSE75%", llvm::ConstantInt::get(llvm->TypeInt, 11)));
    constants.insert(std::make_pair("CHANNEL_PIANO%", llvm::ConstantInt::get(llvm->TypeInt, 64)));
    constants.insert(std::make_pair("CHANNEL_BASS%", llvm::ConstantInt::get(llvm->TypeInt, 65)));
    constants.insert(std::make_pair("CHANNEL_BRASS%", llvm::ConstantInt::get(llvm->TypeInt, 66)));
    constants.insert(std::make_pair("CHANNEL_CYMBAL%", llvm::ConstantInt::get(llvm->TypeInt, 67)));
    constants.insert(std::make_pair("CHANNEL_GLOCKENSPIEL%", llvm::ConstantInt::get(llvm->TypeInt, 68)));
    constants.insert(std::make_pair("CHANNEL_GUITAR%", llvm::ConstantInt::get(llvm->TypeInt, 69)));
    constants.insert(std::make_pair("CHANNEL_ORGAN%", llvm::ConstantInt::get(llvm->TypeInt, 70)));
    constants.insert(std::make_pair("CHANNEL_REED%", llvm::ConstantInt::get(llvm->TypeInt, 71)));
    constants.insert(std::make_pair("NOTE_C0#", llvm::ConstantFP::get(llvm->TypeFloat, 16.35)));
    constants.insert(std::make_pair("NOTE_Cs0#", llvm::ConstantFP::get(llvm->TypeFloat, 17.32)));
    constants.insert(std::make_pair("NOTE_Db0#", llvm::ConstantFP::get(llvm->TypeFloat, 17.32)));
    constants.insert(std::make_pair("NOTE_D0#", llvm::ConstantFP::get(llvm->TypeFloat, 18.35)));
    constants.insert(std::make_pair("NOTE_DS0#", llvm::ConstantFP::get(llvm->TypeFloat, 19.45)));
    constants.insert(std::make_pair("NOTE_Eb0#", llvm::ConstantFP::get(llvm->TypeFloat, 19.45)));
    constants.insert(std::make_pair("NOTE_E0#", llvm::ConstantFP::get(llvm->TypeFloat, 20.60)));
    constants.insert(std::make_pair("NOTE_F0#", llvm::ConstantFP::get(llvm->TypeFloat, 21.83)));
    constants.insert(std::make_pair("NOTE_Fs0#", llvm::ConstantFP::get(llvm->TypeFloat, 23.12)));
    constants.insert(std::make_pair("NOTE_Gb0#", llvm::ConstantFP::get(llvm->TypeFloat, 23.12)));
    constants.insert(std::make_pair("NOTE_G0#", llvm::ConstantFP::get(llvm->TypeFloat, 24.50)));
    constants.insert(std::make_pair("NOTE_Gs0#", llvm::ConstantFP::get(llvm->TypeFloat, 25.96)));
    constants.insert(std::make_pair("NOTE_Ab0#", llvm::ConstantFP::get(llvm->TypeFloat, 25.96)));
    constants.insert(std::make_pair("NOTE_A0#", llvm::ConstantFP::get(llvm->TypeFloat, 27.50)));
    constants.insert(std::make_pair("NOTE_As0#", llvm::ConstantFP::get(llvm->TypeFloat, 29.14)));
    constants.insert(std::make_pair("NOTE_Bb0#", llvm::ConstantFP::get(llvm->TypeFloat, 29.14)));
    constants.insert(std::make_pair("NOTE_B0#", llvm::ConstantFP::get(llvm->TypeFloat, 30.87)));
    constants.insert(std::make_pair("NOTE_C1#", llvm::ConstantFP::get(llvm->TypeFloat, 32.70)));
    constants.insert(std::make_pair("NOTE_Cs1#", llvm::ConstantFP::get(llvm->TypeFloat, 34.65)));
    constants.insert(std::make_pair("NOTE_Db1#", llvm::ConstantFP::get(llvm->TypeFloat, 34.65)));
    constants.insert(std::make_pair("NOTE_D1#", llvm::ConstantFP::get(llvm->TypeFloat, 36.71)));
    constants.insert(std::make_pair("NOTE_Ds1#", llvm::ConstantFP::get(llvm->TypeFloat, 38.89)));
    constants.insert(std::make_pair("NOTE_Eb1#", llvm::ConstantFP::get(llvm->TypeFloat, 38.89)));
    constants.insert(std::make_pair("NOTE_E1#", llvm::ConstantFP::get(llvm->TypeFloat, 41.20)));
    constants.insert(std::make_pair("NOTE_F1#", llvm::ConstantFP::get(llvm->TypeFloat, 43.65)));
    constants.insert(std::make_pair("NOTE_Fs1#", llvm::ConstantFP::get(llvm->TypeFloat, 46.25)));
    constants.insert(std::make_pair("NOTE_Gb1#", llvm::ConstantFP::get(llvm->TypeFloat, 46.25)));
    constants.insert(std::make_pair("NOTE_G1#", llvm::ConstantFP::get(llvm->TypeFloat, 49.00)));
    constants.insert(std::make_pair("NOTE_Gs1#", llvm::ConstantFP::get(llvm->TypeFloat, 51.91)));
    constants.insert(std::make_pair("NOTE_Ab1#", llvm::ConstantFP::get(llvm->TypeFloat, 51.91)));
    constants.insert(std::make_pair("NOTE_A1#", llvm::ConstantFP::get(llvm->TypeFloat, 55.00)));
    constants.insert(std::make_pair("NOTE_As1#", llvm::ConstantFP::get(llvm->TypeFloat, 58.27)));
    constants.insert(std::make_pair("NOTE_Bb1#", llvm::ConstantFP::get(llvm->TypeFloat, 58.27)));
    constants.insert(std::make_pair("NOTE_B1#", llvm::ConstantFP::get(llvm->TypeFloat, 61.74)));
    constants.insert(std::make_pair("NOTE_C2#", llvm::ConstantFP::get(llvm->TypeFloat, 65.41)));
    constants.insert(std::make_pair("NOTE_Cs2#", llvm::ConstantFP::get(llvm->TypeFloat, 69.30)));
    constants.insert(std::make_pair("NOTE_Db2#", llvm::ConstantFP::get(llvm->TypeFloat, 69.30)));
    constants.insert(std::make_pair("NOTE_D2#", llvm::ConstantFP::get(llvm->TypeFloat, 73.42)));
    constants.insert(std::make_pair("NOTE_Ds2#", llvm::ConstantFP::get(llvm->TypeFloat, 77.78)));
    constants.insert(std::make_pair("NOTE_Eb2#", llvm::ConstantFP::get(llvm->TypeFloat, 77.78)));
    constants.insert(std::make_pair("NOTE_E2#", llvm::ConstantFP::get(llvm->TypeFloat, 82.41)));
    constants.insert(std::make_pair("NOTE_F2#", llvm::ConstantFP::get(llvm->TypeFloat, 87.31)));
    constants.insert(std::make_pair("NOTE_Fs2#", llvm::ConstantFP::get(llvm->TypeFloat, 92.50)));
    constants.insert(std::make_pair("NOTE_Gb2#", llvm::ConstantFP::get(llvm->TypeFloat, 92.50)));
    constants.insert(std::make_pair("NOTE_G2#", llvm::ConstantFP::get(llvm->TypeFloat, 98.00)));
    constants.insert(std::make_pair("NOTE_Gs2#", llvm::ConstantFP::get(llvm->TypeFloat, 103.83)));
    constants.insert(std::make_pair("NOTE_Ab2#", llvm::ConstantFP::get(llvm->TypeFloat, 103.83)));
    constants.insert(std::make_pair("NOTE_A2#", llvm::ConstantFP::get(llvm->TypeFloat, 110.00)));
    constants.insert(std::make_pair("NOTE_As2#", llvm::ConstantFP::get(llvm->TypeFloat, 116.54)));
    constants.insert(std::make_pair("NOTE_Bb2#", llvm::ConstantFP::get(llvm->TypeFloat, 116.54)));
    constants.insert(std::make_pair("NOTE_B2#", llvm::ConstantFP::get(llvm->TypeFloat, 123.47)));
    constants.insert(std::make_pair("NOTE_C3#", llvm::ConstantFP::get(llvm->TypeFloat, 130.81)));
    constants.insert(std::make_pair("NOTE_Cs3#", llvm::ConstantFP::get(llvm->TypeFloat, 138.59)));
    constants.insert(std::make_pair("NOTE_Db3#", llvm::ConstantFP::get(llvm->TypeFloat, 138.59)));
    constants.insert(std::make_pair("NOTE_D3#", llvm::ConstantFP::get(llvm->TypeFloat, 146.83)));
    constants.insert(std::make_pair("NOTE_Ds3#", llvm::ConstantFP::get(llvm->TypeFloat, 155.56)));
    constants.insert(std::make_pair("NOTE_Eb3#", llvm::ConstantFP::get(llvm->TypeFloat, 155.56)));
    constants.insert(std::make_pair("NOTE_E3#", llvm::ConstantFP::get(llvm->TypeFloat, 164.81)));
    constants.insert(std::make_pair("NOTE_F3#", llvm::ConstantFP::get(llvm->TypeFloat, 174.61)));
    constants.insert(std::make_pair("NOTE_Fs3#", llvm::ConstantFP::get(llvm->TypeFloat, 185.00)));
    constants.insert(std::make_pair("NOTE_Gb3#", llvm::ConstantFP::get(llvm->TypeFloat, 185.00)));
    constants.insert(std::make_pair("NOTE_G3#", llvm::ConstantFP::get(llvm->TypeFloat, 196.00)));
    constants.insert(std::make_pair("NOTE_Gs3#", llvm::ConstantFP::get(llvm->TypeFloat, 207.65)));
    constants.insert(std::make_pair("NOTE_Ab3#", llvm::ConstantFP::get(llvm->TypeFloat, 207.65)));
    constants.insert(std::make_pair("NOTE_A3#", llvm::ConstantFP::get(llvm->TypeFloat, 220.00)));
    constants.insert(std::make_pair("NOTE_As3#", llvm::ConstantFP::get(llvm->TypeFloat, 233.08)));
    constants.insert(std::make_pair("NOTE_Bb3#", llvm::ConstantFP::get(llvm->TypeFloat, 233.08)));
    constants.insert(std::make_pair("NOTE_B3#", llvm::ConstantFP::get(llvm->TypeFloat, 246.94)));
    constants.insert(std::make_pair("NOTE_C4#", llvm::ConstantFP::get(llvm->TypeFloat, 261.63)));
    constants.insert(std::make_pair("NOTE_Cs4#", llvm::ConstantFP::get(llvm->TypeFloat, 277.18)));
    constants.insert(std::make_pair("NOTE_Db4#", llvm::ConstantFP::get(llvm->TypeFloat, 277.18)));
    constants.insert(std::make_pair("NOTE_D4#", llvm::ConstantFP::get(llvm->TypeFloat, 293.66)));
    constants.insert(std::make_pair("NOTE_Ds4#", llvm::ConstantFP::get(llvm->TypeFloat, 311.13)));
    constants.insert(std::make_pair("NOTE_Eb4#", llvm::ConstantFP::get(llvm->TypeFloat, 311.13)));
    constants.insert(std::make_pair("NOTE_E4#", llvm::ConstantFP::get(llvm->TypeFloat, 329.63)));
    constants.insert(std::make_pair("NOTE_F4#", llvm::ConstantFP::get(llvm->TypeFloat, 349.23)));
    constants.insert(std::make_pair("NOTE_Fs4#", llvm::ConstantFP::get(llvm->TypeFloat, 369.99)));
    constants.insert(std::make_pair("NOTE_Gb4#", llvm::ConstantFP::get(llvm->TypeFloat, 369.99)));
    constants.insert(std::make_pair("NOTE_G4#", llvm::ConstantFP::get(llvm->TypeFloat, 392.00)));
    constants.insert(std::make_pair("NOTE_Gs4#", llvm::ConstantFP::get(llvm->TypeFloat, 415.30)));
    constants.insert(std::make_pair("NOTE_Ab4#", llvm::ConstantFP::get(llvm->TypeFloat, 415.30)));
    constants.insert(std::make_pair("NOTE_A4#", llvm::ConstantFP::get(llvm->TypeFloat, 440.00)));
    constants.insert(std::make_pair("NOTE_As4#", llvm::ConstantFP::get(llvm->TypeFloat, 466.16)));
    constants.insert(std::make_pair("NOTE_Bb4#", llvm::ConstantFP::get(llvm->TypeFloat, 466.16)));
    constants.insert(std::make_pair("NOTE_B4#", llvm::ConstantFP::get(llvm->TypeFloat, 493.88)));
    constants.insert(std::make_pair("NOTE_C5#", llvm::ConstantFP::get(llvm->TypeFloat, 523.25)));
    constants.insert(std::make_pair("NOTE_Cs5#", llvm::ConstantFP::get(llvm->TypeFloat, 554.37)));
    constants.insert(std::make_pair("NOTE_Db5#", llvm::ConstantFP::get(llvm->TypeFloat, 554.37)));
    constants.insert(std::make_pair("NOTE_D5#", llvm::ConstantFP::get(llvm->TypeFloat, 587.33)));
    constants.insert(std::make_pair("NOTE_Ds5#", llvm::ConstantFP::get(llvm->TypeFloat, 622.25)));
    constants.insert(std::make_pair("NOTE_Eb5#", llvm::ConstantFP::get(llvm->TypeFloat, 622.25)));
    constants.insert(std::make_pair("NOTE_E5#", llvm::ConstantFP::get(llvm->TypeFloat, 659.25)));
    constants.insert(std::make_pair("NOTE_Fs5#", llvm::ConstantFP::get(llvm->TypeFloat, 739.99)));
    constants.insert(std::make_pair("NOTE_Gb5#", llvm::ConstantFP::get(llvm->TypeFloat, 739.99)));
    constants.insert(std::make_pair("NOTE_G5#", llvm::ConstantFP::get(llvm->TypeFloat, 783.99)));
    constants.insert(std::make_pair("NOTE_Gs5#", llvm::ConstantFP::get(llvm->TypeFloat, 830.61)));
    constants.insert(std::make_pair("NOTE_Ab5#", llvm::ConstantFP::get(llvm->TypeFloat, 830.61)));
    constants.insert(std::make_pair("NOTE_A5#", llvm::ConstantFP::get(llvm->TypeFloat, 880.00)));
    constants.insert(std::make_pair("NOTE_As5#", llvm::ConstantFP::get(llvm->TypeFloat, 932.33)));
    constants.insert(std::make_pair("NOTE_Bb5#", llvm::ConstantFP::get(llvm->TypeFloat, 932.33)));
    constants.insert(std::make_pair("NOTE_B5#", llvm::ConstantFP::get(llvm->TypeFloat, 987.77)));
    constants.insert(std::make_pair("NOTE_C6#", llvm::ConstantFP::get(llvm->TypeFloat, 1046.50)));
    constants.insert(std::make_pair("NOTE_Cs6#", llvm::ConstantFP::get(llvm->TypeFloat, 1108.73)));
    constants.insert(std::make_pair("NOTE_Db6#", llvm::ConstantFP::get(llvm->TypeFloat, 1108.73)));
    constants.insert(std::make_pair("NOTE_D6#", llvm::ConstantFP::get(llvm->TypeFloat, 1174.66)));
    constants.insert(std::make_pair("NOTE_Ds6#", llvm::ConstantFP::get(llvm->TypeFloat, 1244.51)));
    constants.insert(std::make_pair("NOTE_Eb6#", llvm::ConstantFP::get(llvm->TypeFloat, 1244.51)));
    constants.insert(std::make_pair("NOTE_E6#", llvm::ConstantFP::get(llvm->TypeFloat, 1318.51)));
    constants.insert(std::make_pair("NOTE_F6#", llvm::ConstantFP::get(llvm->TypeFloat, 1396.91)));
    constants.insert(std::make_pair("NOTE_Fs6#", llvm::ConstantFP::get(llvm->TypeFloat, 1479.98)));
    constants.insert(std::make_pair("NOTE_Gb6#", llvm::ConstantFP::get(llvm->TypeFloat, 1479.98)));
    constants.insert(std::make_pair("NOTE_G6#", llvm::ConstantFP::get(llvm->TypeFloat, 1567.98)));
    constants.insert(std::make_pair("NOTE_Gs6#", llvm::ConstantFP::get(llvm->TypeFloat, 1661.22)));
    constants.insert(std::make_pair("NOTE_Ab6#", llvm::ConstantFP::get(llvm->TypeFloat, 1661.22)));
    constants.insert(std::make_pair("NOTE_A6#", llvm::ConstantFP::get(llvm->TypeFloat, 1760.00)));
    constants.insert(std::make_pair("NOTE_As6#", llvm::ConstantFP::get(llvm->TypeFloat, 1864.66)));
    constants.insert(std::make_pair("NOTE_Bb6#", llvm::ConstantFP::get(llvm->TypeFloat, 1864.66)));
    constants.insert(std::make_pair("NOTE_B6#", llvm::ConstantFP::get(llvm->TypeFloat, 1975.53)));
    constants.insert(std::make_pair("NOTE_C7#", llvm::ConstantFP::get(llvm->TypeFloat, 2093.00)));
    constants.insert(std::make_pair("NOTE_Cs7#", llvm::ConstantFP::get(llvm->TypeFloat, 2217.46)));
    constants.insert(std::make_pair("NOTE_Db7#", llvm::ConstantFP::get(llvm->TypeFloat, 2217.46)));
    constants.insert(std::make_pair("NOTE_D7#", llvm::ConstantFP::get(llvm->TypeFloat, 2349.32)));
    constants.insert(std::make_pair("NOTE_Ds7#", llvm::ConstantFP::get(llvm->TypeFloat, 2489.02)));
    constants.insert(std::make_pair("NOTE_Eb7#", llvm::ConstantFP::get(llvm->TypeFloat, 2489.02)));
    constants.insert(std::make_pair("NOTE_E7#", llvm::ConstantFP::get(llvm->TypeFloat, 2637.02)));
    constants.insert(std::make_pair("NOTE_F7#", llvm::ConstantFP::get(llvm->TypeFloat, 2793.83)));
    constants.insert(std::make_pair("NOTE_Fs7#", llvm::ConstantFP::get(llvm->TypeFloat, 2959.96)));
    constants.insert(std::make_pair("NOTE_Gb7#", llvm::ConstantFP::get(llvm->TypeFloat, 2959.96)));
    constants.insert(std::make_pair("NOTE_G7#", llvm::ConstantFP::get(llvm->TypeFloat, 3135.96)));
    constants.insert(std::make_pair("NOTE_Gs7#", llvm::ConstantFP::get(llvm->TypeFloat, 3322.44)));
    constants.insert(std::make_pair("NOTE_Ab7#", llvm::ConstantFP::get(llvm->TypeFloat, 3322.44)));
    constants.insert(std::make_pair("NOTE_A7#", llvm::ConstantFP::get(llvm->TypeFloat, 3520.00)));
    constants.insert(std::make_pair("NOTE_As7#", llvm::ConstantFP::get(llvm->TypeFloat, 3729.31)));
    constants.insert(std::make_pair("NOTE_Bb7#", llvm::ConstantFP::get(llvm->TypeFloat, 3729.31)));
    constants.insert(std::make_pair("NOTE_B7#", llvm::ConstantFP::get(llvm->TypeFloat, 3951.07)));
    constants.insert(std::make_pair("NOTE_C8#", llvm::ConstantFP::get(llvm->TypeFloat, 4186.01)));
    constants.insert(std::make_pair("NOTE_Cs8#", llvm::ConstantFP::get(llvm->TypeFloat, 4434.92)));
    constants.insert(std::make_pair("NOTE_Db8#", llvm::ConstantFP::get(llvm->TypeFloat, 4434.92)));
    constants.insert(std::make_pair("NOTE_D8#", llvm::ConstantFP::get(llvm->TypeFloat, 4698.63)));
    constants.insert(std::make_pair("NOTE_Ds8#", llvm::ConstantFP::get(llvm->TypeFloat, 4978.03)));
    constants.insert(std::make_pair("NOTE_Eb8#", llvm::ConstantFP::get(llvm->TypeFloat, 4978.03)));
    constants.insert(std::make_pair("NOTE_E8#", llvm::ConstantFP::get(llvm->TypeFloat, 5274.04)));
    constants.insert(std::make_pair("NOTE_F8#", llvm::ConstantFP::get(llvm->TypeFloat, 5587.65)));
    constants.insert(std::make_pair("NOTE_Fs8#", llvm::ConstantFP::get(llvm->TypeFloat, 5919.91)));
    constants.insert(std::make_pair("NOTE_Gb8#", llvm::ConstantFP::get(llvm->TypeFloat, 5919.91)));
    constants.insert(std::make_pair("NOTE_G8#", llvm::ConstantFP::get(llvm->TypeFloat, 6271.93)));
    constants.insert(std::make_pair("NOTE_Gs8#", llvm::ConstantFP::get(llvm->TypeFloat, 6644.88)));
    constants.insert(std::make_pair("NOTE_Ab8#", llvm::ConstantFP::get(llvm->TypeFloat, 6644.88)));
    constants.insert(std::make_pair("NOTE_A8#", llvm::ConstantFP::get(llvm->TypeFloat, 7040.00)));
    constants.insert(std::make_pair("NOTE_As8#", llvm::ConstantFP::get(llvm->TypeFloat, 7458.62)));
    constants.insert(std::make_pair("NOTE_Bb8#", llvm::ConstantFP::get(llvm->TypeFloat, 7458.62)));
    constants.insert(std::make_pair("NOTE_B8#", llvm::ConstantFP::get(llvm->TypeFloat, 7902.13)));*/
}